AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'bin/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'

  RunRailsCops: true

Style/AlignHash:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table
  EnforcedLastArgumentHashStyle: ignore_implicit
  SupportedLastArgumentHashStyles: ignore_implicit

Style/DefWithParentheses:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/MethodDefParentheses:
  Enabled: false

Style/Encoding:
  Enabled: false

StringLiterals:
  EnforcedStyle: double_quotes

Style/LineLength:
  Max: 140
  AllowURI: true

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%':  ()
    '%i': '[]'
    '%q': '[]'
    '%Q': '[]'
    '%r': '[]'
    '%s': '[]'
    '%w': '[]'
    '%W': '[]'
    '%x': '[]'

Style/PredicateName:
  NamePrefixBlacklist:
    - is_
    - has_
    - have_
    - the_
    - a_
