common: &common
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  pool: 20

development:
  database: pingu_development
  username: diveboard
  password: diveboard
  <<: *common

test: &test
  database: pingu_test
  username: diveboard
  password: diveboard
  <<: *common

production:
  database: pingu
  username: postgres
  password: postgres

cucumber:
  <<: *test
